### PR TITLE
Commands Overhaul + Extra features and fixes

### PR DESCRIPTION
**Pull request by Intelligent-Cat**
I have done a lot of stuff, hope you actually merge them cause a lot of people would like to use these:

- Added custom prefixes, changeable in config/commands.php and you don't need to worry about character limit, there is none without breaking the commands
- Added a custom magic levels section, disabled by default in config/levels.php
- You can change how many creator points to give for epic and magic levels
- Fixed auto-ban not counting gauntlet demons and daily and weekly stars and demons
- Added a new mod action type called "Magic change" with ID 16
- Separated each command into a file, their codes are now a function that could be called anytime (except !discord)
- Fixed backupGJAccount.php sending two responses for some reason
- Removed Un-command perms due to being nonsense
- Updated JSColor to 2.3.3 (Hope this isn't a commercial usage)

So I guess that's all, please merge.

### CODE REVIEW

**Comment by fancythedeveloper** [comment]
Is it ready for merge yet?

**Comment by fancythedeveloper** [comment]
Is there anything left to do?

**Comment by Intelligent-Cat** [comment]
Nothing but it actually doesnt work

**Comment by Intelligent-Cat** [comment]
This never finished cause gdopenserver lool

**Comment by NoahGMD** [comment]
is this finished?

**Comment by Intelligent-Cat** [comment]
no and never will finish
bye bye i will close this

**Comment by RxNationGaming** [comment]
Bruh

**Pull request closed without merging**
