### PR TITLE
add mod tool

### PR DESCRIPTION
**Pull request by iAndyHD3**

### CODE REVIEW

**Comment by Cvolton** [comment]
would be better if this utilized the permissions system instead of isAdmin, which is not really supposed to be used for anything anymore

**Comment by iAndyHD3** [comment]
ok i will try to make it more universal

**Comment by iAndyHD3** [comment]
well the problem with doing this with permissions is that a true admin permission doesnt exist, and thats what this tool needs. I dont really know what permission to choose because im pretty sure you dont want to give normal elder mods the permission to edit roles. Because of that I think that isAdmin is fine, if not what permission should the tool use?

**Comment by klimer49** [comment]
lool stupid russophob talking

**Review by silverraaa — COMMENTED** [review]
image ???

**Comment by fancythedeveloper** [comment]
> image ???

You're supposed to put the php file in the main tools folder, not in any extra folder it seems.

**Comment by iAndyHD3** [comment]
> > image ???
> 
> You're supposed to put the php file in the main tools folder, not in any extra folder it seems.

Exactly

**Comment by silverraaa** [comment]
> > image ???
> 
> You're supposed to put the php file in the main tools folder, not in any extra folder it seems.

That helped, thanks!

**Comment by arkrafter** [comment]
> lool stupid russophob talking

Bruh

**Pull request closed without merging**
