### PR TITLE
Added timestamp query into !rate command

### LINKED ISSUE #693: rateDate not updated when using !rate command
Fix in commands.php pls

### LINKED ISSUE #771: commands don't set rateDate
see title

### PR DESCRIPTION
**Pull request by EMREOYUN**
Now it can stamp php unix time into rateDate column.

WARNING: Currently, i don't have an active GDPS and these commits are not tested. Please test it before committing in.

fixes #693
fixes #771

### CODE REVIEW

**Comment by RxNationGaming** [comment]
I test it out & works fine!

**Comment by EMREOYUN** [comment]
> I test it out & works fine!

Thank you for testing :)

**Comment by RxNationGaming** [comment]
> > I test it out & works fine!
> 
> Thank you for testing :)

NP :D

**Comment by Cvolton** [comment]
tested to work

**Comment by EMREOYUN** [comment]
> tested to work

Nice :)

**Comment by RxNationGaming** [comment]
Nice! It merged

**Pull request merged**
