### PR TITLE
Legendary rate

### PR DESCRIPTION
**Pull request by MegaSa1nt**

### CODE REVIEW

**Comment by SkyLandYT** [comment]
How to add legendary icon in game?

**Comment by MegaSa1nt** [comment]
> How to add legendary icon in game?

use mod

**Comment by Truffle11** [comment]
im seeing alot of legendary = 0 what is that 0? is it the role id? like do I need to chnage it?

**Comment by MegaSa1nt** [comment]
> im seeing alot of legendary = 0 what is that 0? is it the role id? like do I need to chnage it?

Wdym

**Comment by Truffle11** [comment]
> > im seeing alot of legendary = 0 what is that 0? is it the role id? like do I need to chnage it?
> 
> Wdym

`commandLegendary` int(11) NOT NULL DEFAULT 0,
  `commandUnlegendary` int(11) NOT NULL DEFAULT 0, <--- that 0
do I have to change anything or does this stand for a role id?

**Comment by MegaSa1nt** [comment]
> > > im seeing alot of legendary = 0 what is that 0? is it the role id? like do I need to chnage it?
> > 
> > Wdym
> 
> `commandLegendary` int(11) NOT NULL DEFAULT 0,
>   `commandUnlegendary` int(11) NOT NULL DEFAULT 0, <--- that 0
> do I have to change anything or does this stand for a role id?

Dont change anything
This is default value for columns
You should run added SQL commands, then give yourself perms to run commands in "roles" table

**Comment by Truffle11** [comment]
> > > > im seeing alot of legendary = 0 what is that 0? is it the role id? like do I need to chnage it?
> > > 
> > > 
> > > Wdym
> > 
> > 
> > `commandLegendary` int(11) NOT NULL DEFAULT 0,
> > `commandUnlegendary` int(11) NOT NULL DEFAULT 0, <--- that 0
> > do I have to change anything or does this stand for a role id?
> 
> Dont change anything This is default value for columns You should run added SQL commands, then give yourself perms to run commands in "roles" table

ok done one other question; should the "rate legendary" commands show up in phpmyadmin? is yes how do I make them show up also thanks for the help

**Comment by Truffle11** [comment]
Also when I do !legendary it says "comment uplaod failed please try again later" how do i fix this?

**Comment by MegaSa1nt** [comment]
> ok done one other question; should the "rate legendary" commands show up in phpmyadmin? is yes how do I make them show up also thanks for the help

I didn't get your message lol

Try to run these commands:
```
ALTER TABLE roles ADD COLUMN commandLegendary INT NOT NULL DEFAULT '0' AFTER commandUnepic;

 ALTER TABLE roles ADD COLUMN commandUnlegendary INT NOT NULL DEFAULT '0' AFTER commandLegendary;

ALTER TABLE levels ADD COLUMN starLegendary INT NOT NULL DEFAULT '0' AFTER starEpic;
```

**Comment by MegaSa1nt** [comment]
> Also when I do !legendary it says "comment uplaod failed please try again later" how do i fix this?

Its ok, it means, that command is successfully executed

**Comment by Truffle11** [comment]
> ALTER TABLE roles ADD COLUMN commandLegendary INT NOT NULL DEFAULT '0' AFTER commandUnepic;
> 
>  ALTER TABLE roles ADD COLUMN commandUnlegendary INT NOT NULL DEFAULT '0' AFTER commandLegendary;
> 
> ALTER TABLE levels ADD COLUMN starLegendary INT NOT NULL DEFAULT '0' AFTER starEpic;
> ```

where do I run it lol I dont know to much about this

**Comment by MegaSa1nt** [comment]
> where do I run it lol I dont know to much about this

Open phpmyadmin

Choose your database in the left of page

Open console at bottom of page

Copy commands

Paste and click Ctrl+Enter

**Comment by Truffle11** [comment]
> > where do I run it lol I dont know to much about this
> 
> Open phpmyadmin
> 
> Choose your database in the left of page
> 
> Open console at bottom of page
> 
> Copy commands
> 
> Paste and click Ctrl+Enter

it was there thanks for the help!

**Comment by Truffle11** [comment]
ok last bother I promise, you said you need a mod to see the legendary rating where do I get it?

**Comment by MegaSa1nt** [comment]
> ok last bother I promise, you said you need a mod to see the legendary rating where do I get it?

Idk

**Comment by Truffle11** [comment]
> Idk

 💀

**Comment by Truffle11** [comment]
is it possible or were you joking

**Comment by MegaSa1nt** [comment]
> is it possible or were you joking
> 

Yes, but i dont know any mod, that does that

**Comment by Truffle11** [comment]
> Yes, but i dont know any mod, that does that

ok so theres no mod I only brought that up cause of 
>>MegaSa1nt
>>How to add legendary icon in game?

>use mod
so How Do you do it?

**Comment by MegaSa1nt** [comment]
> > Yes, but i dont know any mod, that does that
> 
> ok so theres no mod I only brought that up cause of
> 
> > > MegaSa1nt
> > > How to add legendary icon in game?
> 
> > use mod
> 
> so How Do you do it?

i dont know

**Comment by MegaSa1nt** [comment]
> > Yes, but i dont know any mod, that does that
> 
> ok so theres no mod I only brought that up cause of
> 
> > > MegaSa1nt
> > > How to add legendary icon in game?
> 
> > use mod
> 
> so How Do you do it?

it just shows epic rating ingame, while being legendary

**Comment by CoderQCFromScraatch** [comment]
@MegaSa1nt I'm a modder. How would I make it?

**Comment by MegaSa1nt** [comment]
> @MegaSa1nt I'm a modder. How would I make it?

As for now legendary tricks game to think, that level is featured and epic at the same time, so you can do something in this way

**Comment by CoderQCFromScraatch** [comment]
> > @MegaSa1nt I'm a modder. How would I make it?
> 
> As for now legendary tricks game to think, that level is featured and epic at the same time, so you can do something in this way

How would I replace the aura near the difficulty face?

**Comment by MegaSa1nt** [comment]
> How would I replace the aura near the difficulty face?

Idk, im not modder

**Comment by CoderQCFromScraatch** [comment]
Time to make this myself.

**Comment by MegaSa1nt** [comment]
No need, cuz 2.2

**Pull request closed without merging**
