### PR TITLE
Suggest system

### PR DESCRIPTION
**Pull request by bit0r1n**
_re-create cuz shit code_
Added new function (`suggestLevel`) into `mainLib.php`
Edited `suggestGJStars.php`
Added new file (`/tools/stats/suggestList.php access have users with permission actionRateStars and commandRate`)
Added new table `suggest`

### CODE REVIEW

**Comment by DarkGD123** [comment]
So how 2 use this

**Comment by bit0r1n** [comment]
@DarkGD123 lol, ok..
You suggest level with in-game mod button (left blue button), or if you admin - you rate this level
Level sent to `suggest` table
In `suggestList.php` you can view levels from table `suggest`

**Comment by bit0r1n** [comment]
With current mod button you can only rate level ¯\_(ツ)_/¯

**Comment by Zaxior** [comment]
How to sent levels? After merge that on my GDPS mods still can rate levels

**Comment by bit0r1n** [comment]
@Zaxior 
if account have permission `actionRequestMod` and don't have `actionRateStars` , just click to mod button in level
sending
*result in database*
db
and result in `suggestList.php` *i delete tools folder from server, but i created page for dashboard, kek`
list

**Comment by Zaxior** [comment]
thx for help

**Comment by Zaxior** [comment]
Still doesn't work...

**Comment by bit0r1n** [comment]
@Zaxior 🤔
what kind of error?
on file error_log?
or you incorrectly configured role?
or what?

**Comment by Zaxior** [comment]
Oh I fixed it myself... Can you tell me how to setup a role that can give rate without stae and can't rate lvl with stars but can send star rate to owner?

**Comment by bit0r1n** [comment]
So, you want to do >
If level has stars - mod can't rate again this level
and
If level doesn't has stars - mod can rate level
aand
If ??? - mod can send suggest to owner
?

**Comment by Zaxior** [comment]
Nevermind.... By the way I take away mod from X, but after take away X still can send level. You know how to fix it?

**Comment by bit0r1n** [comment]
> Nevermind.... By the way I take away mod from X, but after take away X still can send level. You know how to fix it?

idk, do this without my code (suggestGJStars.php), maybe gd bug lol

**Comment by DoggoTaco** [comment]
Tried to replace databases for the .exe's but it just wont work. when i used the original it worked. i also had a error with importing the sql but it worked?

**Comment by Cancre** [comment]
How can I install this ?

**Comment by DarkGD123** [comment]
When I sent something it rates the leve even though actionRateStars=0 ?
How do I fix it? @bit0r1n

**Comment by DarkGD123** [comment]
Screenshot_2019-05-08_064302
Screenshot_2019-05-08_064329

**Comment by ItzElectrix** [comment]
When I try to go to /dashboard/stats/suggestList.php, it gives me an error even though the file exists in the directory. How do I fix this?

Capture

**Comment by bit0r1n** [comment]
@ItzElectrix file exists in location ~/tools/stats

**Comment by bit0r1n** [comment]
@DarkGD123 lol
idk, it perfectly work for me

**Comment by DarkGD123** [comment]
@bit0r1n When I Sent A Level It will get rated even though actionRateStar=0

**Comment by bit0r1n** [comment]
> 
> 
> @bit0r1n When I Sent A Level It will get rated even though actionRateStar=0

i really dont know how to help you. i created new server, merged my pr, created role with one permission(actionRequestMod=1), i send level and level didn't get rate. maybe you have admin permission?

**Comment by DarkGD123** [comment]
isAdmin=1 @bit0r1n

**Comment by bit0r1n** [comment]
> 
> 
> isAdmin=1 @bit0r1n

this is a reason why you cant suggest level

**Comment by DarkGD123** [comment]
So isAdmin=0?

**Comment by bit0r1n** [comment]
yes

**Comment by DarkGD123** [comment]
Also @bit0r1n how do I get notifications of it when someone send a level via discord..I think it uses webhook

**Comment by bit0r1n** [comment]
> 
> 
> Also @bit0r1n how do I get notifications of it when someone send a level via discord..I think it uses webhook

you can use function `sendDiscordPM('user_id_or_what', 'message')` from `mainLib.php`

**Comment by DarkGD123** [comment]
Ok

**Comment by bit0r1n** [comment]
k i will create new pr without shit commits

**Pull request closed without merging**
