### PR TITLE
Unlist levels are also displayed in 'My Online Levels'

### PR DESCRIPTION
**Pull request by RedLime**
that's all too

### CODE REVIEW

**Comment by Jecket22** [comment]
blame rob

**Comment by fancythedeveloper** [comment]
Nah, make this an option if you want people's unlisted levels to show in their Online Levels list too

**Comment by NoahGMD** [comment]
yea because in robtop's servers it shows unlisted level in "my online levels"

**Comment by RedLime** [comment]
> Nah, make this an option if you want people's unlisted levels to show in their Online Levels list too

Only player own unlisted level is shown, I don't know it need an option

**Review by anonymousGDplayer — APPROVED** [review]

**Comment by anonymousGDplayer** [comment]
cool

**Comment by Cvolton** [comment]
doesn't validate GJP

**Comment by RedLime** [comment]
> doesn't validate GJP

Unfortunately, that fork doesn't exist for now. :(

**Pull request closed without merging**
