### PR TITLE
Fixed issue with NOT unlisted levels not being able to download without being friends with author

### PR DESCRIPTION
**Pull request by MegaSa1nt**

### CODE REVIEW

**Comment by Cvolton** [comment]
considering the fact that 0 is the default value for this column, i'd like to see how this can be reproduced?

**Comment by MegaSa1nt** [comment]
> considering the fact that 0 is the default value for this column, i'd like to see how this can be reproduced?

Idk why, but reuploading levels make this column bigger than 1
Level search doesnt show only unlisted2 = 1, but non friends check doesnt let you download levels with unlisted2 > 0, that means public levels cant be downloaded without being friends

**Comment by Cvolton** [comment]
level search is based on unlisted, not unlisted2

the actual bug at hand seems to be that unlisted2 is getting assigned a non-zero value even if it's not supposed to be friends only but i can't replicate that at all

**Comment by MegaSa1nt** [comment]
> the actual bug at hand seems to be that unlisted2 is getting assigned a non-zero value even if it's not supposed to be friends only but i can't replicate that at all

thats what i tried to fix

**Pull request closed without merging**
