### PR TITLE
Today I will show you how to make an iOS version of a GDPS.

### PR DESCRIPTION
**Pull request by hiimjustin000**
# Today I will show you how to make an iOS version of a GDPS.

### This is a solution to these issues:

- **#372**
- **#355** 
- **#311** 
- **#287**
- **#400** 

### So, let's get started.

- **Download the IPA from https://ipswbeta.com/download-geometry-dast-iphoneipadipod-completely-free-latest-version/**

- **Extract it by using WinRAR Archiver (https://rarlab.com)**

- **Go to Geometry Dash [RobTop Games AB] (v2.11 v2.1.1 Univ LP os80)-Ghay.rc336_932/Payload/Geometry Dash.app/GeometryJump and open your text editor**

- **Replace the Boomlings URL with your URL (Don't forget Base64 OwO) and save the file**

- **Compress as ZIP and rename it to an IPA (Make sure you have hide file extensions off)**

- **Done.**

### Figured this out by myself, hope this helps.

### CODE REVIEW

**Comment by hiimjustin000** [comment]
# Compress these files
Capture 56

**Comment by DarkGD123** [comment]
Download doesn't exist

**Comment by DarkGD123** [comment]
Yo wheres the file though

**Comment by hiimjustin000** [comment]
### @DarkGD123 
  **Updated.**

**Comment by DarkGD123** [comment]
After I do the stuff how do I let them download the file?

**Comment by DarkGD123** [comment]
Also where's the website

**Comment by EMREOYUN** [comment]
Wrong Section. Soon can be added to Wiki.

**Comment by hiimjustin000** [comment]
### @DarkGD123 upload it to a media sharing website like Mediafire

**Comment by EMREOYUN** [comment]
Moved to [test](url)

**Comment by EMREOYUN** [comment]
@hiimjustin000 Here is my IPA file compiled by your guide: [Download](http://download.emreoyun.xyz/EOGD.ipa). Can you test it? (We have only 4-5 levels uploaded and 2 registered users)

**Comment by hiimjustin000** [comment]
@EMREOYUN uHhHhHhHhHhH i'M oN wInDhOeS sO I cAnT dO iT

**Comment by EMREOYUN** [comment]
@hiimjustin000 Tested via browserstack.com and results:
Creating Account and Login works well.
Creating level and sending works well.
Listing levels DOESN'T WORK.
Listing Daily, Featured, Gauntlets etc. DOESN'T WORK.
Listing Players DOESN'T WORK.
Player Actions (Mail,Friend etc.) works, but getting error sometimes so DOESN'T WORK.

So we need test on a real device. Until that time, IOS version doesn't work.

**Comment by hiimjustin000** [comment]
CLOSING PULL REQUEST BECAUSE I'M DELETING THE BRANCH. GO TO #468

**Pull request closed without merging**
