### PR TITLE
permission system

### PR DESCRIPTION
**Pull request by AggPro**
needs fixing with the }

### CODE REVIEW

**Comment by Cvolton** [comment]
if I end up implementing this, I want some configurability... also your way of implementing stuff just breaks everything (people with perm level 2 are unable to access perm level 1 commands)

**Comment by AggPro** [comment]
i fixed that issue about people with perm level 2 are unable to access perm level 1 commands.

still }s are missing ;3;

**Comment by AggPro** [comment]
also idkhow2php, just copypasting code hoping it will get fixed and approved xd

**Comment by Jecket22** [comment]
Why not copy and pasting the same commands from perm level 1 to perm level 2 (and so on) too? (Not sure if this mess up anything though)

**Pull request closed without merging**
