### PR TITLE
2.2 update (Lists and other fixes to 2.2)

### PR DESCRIPTION
**Pull request by MegaSa1nt**
## This PR is ready for using on 2.2 GDPSs!

Already did:
- List uploading and updating
- Commenting
- The Safe
- SFX
- List rewards
- List searching filters
- Commands for lists
- Different errors for lists
- Platformer leaderboards
- Autoban
- New search filters
- Downloading songs and SFXs used in level

Doing:
- Nothing

New list commands:
- `!rate` (`!r`) `reward amount` `difficulty (-1 - 10 or by name)` `featured (0 or 1)` `amount of levels required to get reward`
- `!feature` (`!f`) `0 or 1`
- `!unlist` (`!un`) `0 or 1` (1 is unlisted, 0 is public)
- `!delete` (`!d`)
- `!setacc` (`!acc`) `account name or ID`

### CODE REVIEW

**Comment by Kingminer7** [comment]
I noticed a new URL in the exe: https://www.geometrydash.com/database/uploadMPComment.php - Not sure what it does, but I wanted to mention it in case you do.

**Comment by MegaSa1nt** [comment]
`uploadMPComment.php` — Upload MultiPlayer Comment? maybe its related to Versus mode, which is delayed

**Comment by Kingminer7** [comment]
> `uploadMPComment.php` — Upload MultiPlayer Comment? maybe its related to Versus mode, which is delayed

yeah that makes sense, and robtop said he would have versus on different servers, so it makes sense it's on geometrydash.com instead of boomlings.com

**Comment by Kingminer7** [comment]
rating lists with !rate doesn't work, just sends "Comment upload failed. Try again later."

**Comment by MegaSa1nt** [comment]
are you sure you updated to latest version? works for me

**Comment by Kingminer7** [comment]
yeah, just updated less than half an hour ago. even updated sql.

**Comment by Kingminer7** [comment]
Here's my error: Reason: Command failed! Error: SQLSTATE[22007]: Invalid datetimeformat: 1366 Incorrect integer value: '' for column `id20294813

**Comment by MegaSa1nt** [comment]
can you tell file and line? cant reproduce on my gdps

**Comment by Kingminer7** [comment]
temp_0_Command failed! Error: 
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `(database)`.`lists`.`starStars` at row 1
 File database/incl/lib/commands.php line 265

**Comment by Kingminer7** [comment]
wait thats for typing string hang on

**Comment by Kingminer7** [comment]
wait hang on i just didn't have enough arguments

**Comment by thejulfor** [comment]
Гаунтлеты почему то багаются
image

**Comment by MegaSa1nt** [comment]
Баг 2.2, гаунтлеты на второй странице

**Comment by Uproxide** [comment]
its being stupid with accounts, making it where you have to refresh everytime

Screenshot 2023-12-24 005633

**Comment by Uproxide** [comment]
also whats the sql script to create the SFX table?

**Comment by MegaSa1nt** [comment]
> its being stupid with accounts, making it where you have to refresh everytime
> 
> Screenshot 2023-12-24 005633
> 

Strange, doesnt happen to me

**Comment by Uproxide** [comment]
i fixed it, it was a problem with the color3 not existing, anyways, how do i add shit to the music library and SFX? there isnt anything in the songs table or anything

**Comment by MegaSa1nt** [comment]
> also whats the sql script to create the SFX table?

There's no script to do that, we're taking SFXs from Rob's server

**Comment by Uproxide** [comment]
oh, then why isnt it there?

**Comment by Uproxide** [comment]
also whgenever you comment on a list it takes it as a command

**Comment by MegaSa1nt** [comment]
> oh, then why isnt it there?

Are you sure you applied all files?

**Comment by MegaSa1nt** [comment]
> also whgenever you comment on a list it takes it as a command
> 

Thanks, will check later

**Comment by Kingminer7** [comment]
wait doesn't cvolton usually update the database.sql whenever an update sql is added to the folder?

**Comment by MegaSa1nt** [comment]
> wait doesn't cvolton usually update the database.sql whenever an update sql is added to the folder?

yes, i forgot

**Comment by Kingminer7** [comment]
i couldn't get sound effects to work. i disabled the php server and started a custom node.js server that prints out post requests, and no request came through for sfx or songs. is it on a server that isn't boomlings?

**Comment by MegaSa1nt** [comment]
did you put [this file](https://github.com/MegaSa1nt/GMDprivateServer/blob/lists/getCustomContentURL.php) to your gdps?

**Comment by Kingminer7** [comment]
yea its been there
image

**Comment by Kingminer7** [comment]
wait i think its a steam emulator im using, maybe it goes through steam to get the content somehow

**Comment by thejulfor** [comment]
У меня почему то не работают листы и сейф.. У меня ощущение, что я неправильно как то заменил адрес в hxd, потому что если отправить такой же POST запрос через какой нибудь сайт, то он  выдаст мне тот лист, который я создал вручную в базе данных (выкладывать также не могу)
Там же изменилось то, как надо заменять адрес. Подскажи, как сделать правильно, можешь даже в дс написать так удобнее будет (@julfor)

**Comment by thejulfor** [comment]
> its being stupid with accounts, making it where you have to refresh everytime
> 
> Screenshot 2023-12-24 005633

А еще у меня такая же проблема как у этого чела

**Comment by Uproxide** [comment]
How does the command go for !rate on lists?

**Comment by Joxlyn** [comment]
There is a bug in the lists where the "likes" do not increase

**Comment by Uproxide** [comment]
this is so cool guys

**Comment by pastadudes** [comment]
why tf is this not merged?

**Comment by CustomGameGD** [comment]
Screenshot 2023-12-25 114053
how to fix this bug in top list?

**Comment by smpial** [comment]
Я ещё не проверял этот код, но хочу спросить, а в поиске готова кнопка для показа уровней, которые были отправлены модераторам? И отправлять уровни туда могут же только обычные модераторы, да?

**Comment by MegaSa1nt** [comment]
> Я ещё не проверял этот код, но хочу спросить, а в поиске готова кнопка для показа уровней, которые были отправлены модераторами? И отправлять уровни туда могут же только обычные модераторы, да? 

Да, всё верно, и тоже самое относится и к листам

**Comment by MegaSa1nt** [comment]
> Screenshot 2023-12-25 114053
> how to fix this bug in top list?

Strange, shouldn't happen, did you manually added some list?

**Comment by MegaSa1nt** [comment]
> There is a bug in the lists where the "likes" do not increase

Are you sure you applied all files and SQLs correctly? Works for me

**Comment by CustomGameGD** [comment]
> > Screenshot 2023-12-25 114053
> > how to fix this bug in top list?
> 
> Strange, shouldn't happen, did you manually added some list?

I added in gdps

**Comment by MegaSa1nt** [comment]
> > Strange, shouldn't happen, did you manually added some list?
> 
> I added in gdps. it only shows the level when i have downloaded the level before in gdps

try now, should be fixed

**Comment by Joxlyn** [comment]
> > There is a bug in the lists where the "likes" do not increase
> 
> Are you sure you applied all files and SQLs correctly? Works for me

Yes, in fact that happens when you refresh the list.

when I enter the list and click "like" it is displayed correctly but when I leave the list and refresh the "Likes" are not saved.

Giving "Like" to the list:
GDPS01
GDPS02
GDPS03

I refresh the list and the "like" disappears:
GDPS04

**Comment by Joxlyn** [comment]
> > There is a bug in the lists where the "likes" do not increase
> 
> Are you sure you applied all files and SQLs correctly? Works for me

Yes, in fact that happens when you refresh the list.
when I enter the list and click "like" it is displayed correctly but when I leave the list and refresh the "Likes" are not saved.

Giving "Like" to the list:
GDPS01
GDPS02
GDPS03

I refresh the list and the "like" disappears:
GDPS04

**Comment by MegaSa1nt** [comment]
try updating this file: https://github.com/MegaSa1nt/GMDprivateServer/blob/lists/incl/misc/likeGJItem.php

**Comment by Joxlyn** [comment]
> try updating this file: https://github.com/MegaSa1nt/GMDprivateServer/blob/lists/incl/misc/likeGJItem.php

Yes, I have updated that file (I even re-uploaded it to my server) but it still doesn't work.

**Comment by Uproxide** [comment]
Couldnt i make my own webpage to host SFX and Music Library?
Cause if i could, i was wondering how it would look (like in the ftp, like is it httpdocs/sfx and httpdocs/music?

**Comment by mahierth** [comment]
how do i use this

**Comment by MegaSa1nt** [comment]
> Couldnt i make my own webpage to host SFX and Music Library?
> Cause if i could, i was wondering how it would look (like in the ftp, like is it httpdocs/sfx and httpdocs/music?
> 

SFX and Music libraries are encrypted and stored in .dat, if you decrypt it, then you can

**Comment by MegaSa1nt** [comment]
> how do i use this

Same as original GMDPrivateServer

**Comment by mahierth** [comment]
> > how do i use this
> 
> Same as original GMDPrivateServer

do you mean Cvolton's GMDprivateServer or yours?

**Comment by MegaSa1nt** [comment]
> do you mean Cvolton's GMDprivateServer or yours?

Cvolton's

**Comment by mahierth** [comment]
> > do you mean Cvolton's GMDprivateServer or yours?
> 
> Cvolton's

oh alr

**Comment by mahierth** [comment]
> > do you mean Cvolton's GMDprivateServer or yours?
> 
> Cvolton's

ok

when i use your gmdprivateserver (in the gdps itself, not the dashboard) it doesnt let me login, it says "login failed" and when i try to register it says "something went wrong" what do i do

**Comment by MegaSa1nt** [comment]
are you sure you applied SQL? https://github.com/MegaSa1nt/GMDprivateServer/blob/lists/_updates/2023-12-20.sql

**Comment by smpial** [comment]
> > Couldnt i make my own webpage to host SFX and Music Library?
> > Cause if i could, i was wondering how it would look (like in the ftp, like is it httpdocs/sfx and httpdocs/music?
> 
> SFX and Music libraries are encrypted and stored in .dat, if you decrypt it, then you can

@MegaSa1nt dat файлы звуков и музыки - это просто сжатый текст с помощью deflate и закодированный в base64, его можно легко расшифровать

**Comment by MegaSa1nt** [comment]
> @MegaSa1nt dat файлы звуков и музыки - это просто сжатый текст с помощью deflate и закодированный в base64, его можно легко расшифровать
> 

О, класс, спасибо

**Comment by smpial** [comment]
А можно добавлять unlisted уровни в список и будут ли они видны другим игрокам? Я просто хочу скрыть некоторые уровни из поиска, но добавить их в отдельный список

**Comment by MegaSa1nt** [comment]
> А можно добавлять unlisted уровни в список и будут ли они видны другим игрокам? Я просто хочу скрыть некоторые уровни из поиска, но добавить их в отдельный список
должны быть видны

**Comment by Uproxide** [comment]
@smpial как это сделать?

**Comment by smpial** [comment]
> @smpial как это сделать?

что именно?

**Comment by MegaSa1nt** [comment]
> что именно?

https://github.com/Cvolton/GMDprivateServer/pull/1043#issuecomment-1869603586

**Comment by smpial** [comment]
Nodejs:
let decoded = Buffer.from(file_data, 'base64');
let data = zlib.gunzipSync(decoded);

**Comment by Uproxide** [comment]
@MegaSa1nt Gauntlets still dont fully work, is there any way to fix this?

**Comment by MegaSa1nt** [comment]
> @MegaSa1nt Gauntlets still dont fully work, is there any way to fix this?
> 

There is one base64 link and its required for gauntlets to work

**Comment by Kingminer7** [comment]
> > @MegaSa1nt Gauntlets still dont fully work, is there any way to fix this?
> 
> There is one base64 link and its required for gauntlets to work

I know this is a closed pull, but gauntlets work fine without any base64 urls for me..? I have steam if thats any different

**Comment by MegaSa1nt** [comment]
> I know this is a closed pull, but gauntlets work fine without any base64 urls for me..? I have steam if thats any different

try to load levels

**Comment by Kingminer7** [comment]
> > I know this is a closed pull, but gauntlets work fine without any base64 urls for me..? I have steam if thats any different
> 
> try to load levels

oh i see. what's the url though? i searched for base64 encoded boomlings.com and nothing showed.

**Comment by Aussiergd** [comment]
Trying to rate lists but nothing is working. I tried all the commands. I know how to feature it, but how do I make it where you claim diamonds from it. I did !r 50 and nothing happened.

**Comment by Aussiergd** [comment]
Says comment upload failed

I did !r 50 hard

**Comment by Aussiergd** [comment]
Featuring lists work for me but giving them rewards doesn't. I even tried doing it in phpmyadmin.

image

**Comment by MegaSa1nt** [comment]
you have old 2.2 version, run these commands in SQL:
```sql
ALTER TABLE `levels` ADD `songs` VARCHAR(2048) NOT NULL DEFAULT '' AFTER `songID`, ADD `sfxs` VARCHAR(2048) NOT NULL DEFAULT '' AFTER `songs`, ADD `ts` INT NOT NULL DEFAULT '0' AFTER `wt2`;
ALTER TABLE `levels` CHANGE `songs` `songIDs` VARCHAR(2048) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '';
ALTER TABLE `levels` CHANGE `sfxs` `sfxIDs` VARCHAR(2048) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '';
ALTER TABLE `lists` DROP `userName`;
ALTER TABLE `lists`  ADD `countForReward` INT NOT NULL DEFAULT '0' AFTER `listlevels`;
ALTER TABLE `levels` CHANGE `songIDs` `songIDs` VARCHAR(2048) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NULL DEFAULT '';
ALTER TABLE `levels` CHANGE `sfxIDs` `sfxIDs` VARCHAR(2048) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NULL DEFAULT '';
```

**Comment by Aussiergd** [comment]
How do I get moons to show up on profiles too. Maybe its a phpmyadmin thing aswell that I need to put a command in aswell. Because moons won't display the correct count that people actually have.

**Comment by MegaSa1nt** [comment]
> How do I get moons to show up on profiles too. Maybe its a phpmyadmin thing aswell that I need to put a command in aswell. Because moons won't display the correct count that people actually have.

Are you sure you applied all SQLs for 2.2?

**Comment by Aussiergd** [comment]
I tried importing 2023-12-20 (1).sql on phpmyadmin but it says this:

Error
SQL query: [Copy](https://phpmyadmin.alwaysdata.com/phpmyadmin/index.php?route=/import#)


CREATE TABLE `lists` (
 `listID` int(11) NOT NULL AUTO_INCREMENT,
 `listName` varchar(2048) NOT NULL,
 `listDesc` varchar(2048) NOT NULL,
 `listVersion` int(11) NOT NULL DEFAULT '1',
 `accountID` int(11) NOT NULL,
 `userName` varchar(2048) NOT NULL,
 `downloads` int(11) NOT NULL DEFAULT '0',
 `starDifficulty` int(11) NOT NULL,
 `likes` int(11) NOT NULL DEFAULT '0',
 `starFeatured` int(11) NOT NULL DEFAULT '0',
 `starStars` int(11) NOT NULL DEFAULT '0',
 `listlevels` varchar(2048) NOT NULL,
 `uploadDate` int(11) NOT NULL DEFAULT '0',
 `updateDate` int(11) NOT NULL DEFAULT '0',
 `original` int(11) NOT NULL DEFAULT '0',
 `unlisted` int(11) NOT NULL DEFAULT '0',
 PRIMARY KEY (`listID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
MySQL said: Documentation

#1050 - Table 'lists' already exists

**Comment by Aussiergd** [comment]
Its just weird because it says some of its already in there such as the lists. Its really annoying because I want the moons to work and also sfx too

**Comment by MegaSa1nt** [comment]
> How do I get moons to show up on profiles too. Maybe its a phpmyadmin thing aswell that I need to put a command in aswell. Because moons won't display the correct count that people actually have.

Try to apply these SQLs:
https://github.com/Cvolton/GMDprivateServer/blob/lists/_updates/2022-07-14.sql
https://github.com/Cvolton/GMDprivateServer/blob/lists/_updates/2023-11-23.sql

**Comment by Aussiergd** [comment]
> > How do I get moons to show up on profiles too. Maybe its a phpmyadmin thing aswell that I need to put a command in aswell. Because moons won't display the correct count that people actually have.
> 
> Try to apply these SQLs: https://github.com/Cvolton/GMDprivateServer/blob/lists/_updates/2022-07-14.sql https://github.com/Cvolton/GMDprivateServer/blob/lists/_updates/2023-11-23.sql

Error



ALTER TABLE `users` ADD `moons` INT NOT NULL DEFAULT '0' AFTER `diamonds`;
MySQL said: Documentation

#1060 - Duplicate column name 'moons'

**Comment by Aussiergd** [comment]
It says moons are already in the phpmyadmin but It doesn't show anything in game. It just shows 0 moons on everyones profile.

**Comment by MegaSa1nt** [comment]
are you sure you updated all files? https://github.com/MegaSa1nt/GMDprivateServer/tree/lists

**Comment by Uproxide** [comment]
quick question, how do i make it where the recent tab will show some other level that isnt the recent tab? ik its probably in getGJLevels

**Comment by MegaSa1nt** [comment]
What

**Comment by Uproxide** [comment]
pretty much instead of showing recent levels, it shows 1 specified level (ik how to do it, i dont know what case the recent tab is)

**Comment by MegaSa1nt** [comment]
Type 4

**Comment by MegaSa1nt** [comment]
> @MegaSa1nt dat файлы звуков и музыки - это просто сжатый текст с помощью deflate и закодированный в base64, его можно легко расшифровать

@smpial не сработал ни zlib.inflateRawSync, ни zlib.gunzipSync, ни zlib.unzipSynс, что я делаю не так? при zlib.inflateRawSync ошибка `invalid code lengths set`, при остальных `incorrect header check`

**Pull request merged**
