### PR TITLE
More fixes to 2.2

### PR DESCRIPTION
**Pull request by MegaSa1nt**
Ready to merge!

Fixed:
- Platformer leaderboards
- New Gauntlets names
- Autoban
- Shards (by TheJulfor)
- Demons/stars/moons count

### CODE REVIEW

**Comment by MegaSa1nt** [comment]
huh? why are there old commits

**Comment by Neejik** [comment]
hi, is it normal if my account says "Something went wrong..." when I change my accID to 71?

**Comment by MegaSa1nt** [comment]
1. relogin lol
2. strange

**Comment by Neejik** [comment]
u right, srry I was trying that at 5am, my brain wasn't braining

**Comment by Neejik** [comment]
HELP
image
I tried creating and saving levels but data size doesn't seems to be affected, it's always 0.05

**Comment by MegaSa1nt** [comment]
lol, never saw that size text

**Comment by DaniMx7** [comment]
One question, It's just me or cron.php and fixcps.php doesn't work in any branch at 2.2?

**Comment by MegaSa1nt** [comment]
are you sure you updated these/all files?

**Comment by DaniMx7** [comment]
> are you sure you updated these/all files?

I uninstalled my old files and installed all the new files,so I think yes

**Comment by DaniMx7** [comment]
> > are you sure you updated these/all files?
> 
> I uninstalled my old files and installed all the new files,so I think yes

I tried with your branches "lists" and "listscopy" and with Cvolton's "lists", none worked, I don't know what I'm doing wrong

**Comment by MegaSa1nt** [comment]
> I tried with your branches "lists" and "listscopy" and with Cvolton's "lists", none worked, I don't know what I'm doing wrong

did you applied SQL? https://github.com/MegaSa1nt/GMDprivateServer/blob/lists/_updates/2023-12-20.sql

**Comment by DaniMx7** [comment]
> > I tried with your branches "lists" and "listscopy" and with Cvolton's "lists", none worked, I don't know what I'm doing wrong
> 
> 
> 
> did you applied SQL? https://github.com/MegaSa1nt/GMDprivateServer/blob/lists/_updates/2023-12-20.sql

Honestly I don't know XD. How can I do it?

**Comment by MegaSa1nt** [comment]
> Honestly I don't know XD. How can I do it?

Import file i provided to you

**Comment by DaniMx7** [comment]
> > Honestly I don't know XD. How can I do it?
> 
> Import file i provided to you

Nothing, keeps happening the same. And when I import SQL I get an error.
Captura de pantalla 2024-01-01 165939
Captura de pantalla 2024-01-01 165957
Captura de pantalla 2024-01-01 170942

**Comment by MegaSa1nt** [comment]
Very strange, will check later

About error after import — it means you already imported this file/imported database which contains all SQL changes

**Comment by DaniMx7** [comment]
> Very strange, will check later
> 
> About error after import — it means you already imported this file/imported database which contains all SQL changes

Okey thank you. I appreciate it :)

**Comment by Neejik** [comment]
> lol, never saw that size text

@MegaSa1nt it's 2.2 text
I'm using your 2.2 dashboard and after so many tries I only could be able to make some theories:
1. Server port is broken, when you change servers in HxD, in 2.2 only appears 57 changes made without encode and 1 with domain encode (since in 2.11 used to appears as 32 and 22 changes made)
2. Database files are broken, since I ported my GDPS I only edited the Dashboard and made some changes to the chest rewards, activate `security.php` for captcha, delete `registerGJAccount.php`, decrease Top 100 to Top 10 and delete sakujes joke
3. My GD is broken, after all, I port my GDPS with a pirated GD, something must be missing...

There's also some problems I experimented with your Dashboard, but if you can provide me your Discord, maybe we can talk faster about it

**Comment by MegaSa1nt** [comment]
I'm not home, i'll leave my Discord when come back

**Comment by CustomGameGD** [comment]
Screenshot 2024-01-13 150435
"My Online Level" does not show the level while the server and everything else works normally

**Pull request merged**
