### PR TITLE
Suggested levels in magic instead of 10000+ objects

### LINKED ISSUE #931: Magic category improvement
Does anyone have any suggestions on how to improve the magic category algorithm? For example choose levels that have a lot of downloads & level's age <= 7 days.

### PR DESCRIPTION
**Pull request by MegaSa1nt**
Fixes #931

Note: there is "Sent" button in 2.2, so there's no need for this PR, but i'll keep it for <2.2

### CODE REVIEW

**Comment by Neejik** [comment]
Will you update this feature? I really wanna add it but with the new and older versions of the repo, levels tends to disappear and idk why, any idea?

**Comment by MegaSa1nt** [comment]
@Neejik done

**Comment by Neejik** [comment]
@MegaSa1nt well, it works fine but for some reason, leaderboards and accounts doesn't load, it has relation with the GJPCheck.php file but I still don't understand why
image

**Comment by MegaSa1nt** [comment]
> @MegaSa1nt well, it works fine but for some reason, leaderboards and accounts doesn't load, it has relation with the GJPCheck.php file but I still don't understand why image

I don't really know, cuz only file i changed in this PR — getGJLevels.php

**Pull request closed without merging**
