### PR TITLE
Fix for users without an account

### PR DESCRIPTION
**Pull request by nixide1**
Fixes leaderboards and comments for users without an account

### CODE REVIEW

**Comment by Cvolton** [comment]
this breaks submitting user scores for unregistered users if unregistered submissions are enabled

**Comment by nixide1** [comment]
should work now

**Comment by Cvolton** [comment]
wait why does this exit with -1 if gameVersion is below 2.0

**Comment by nixide1** [comment]
i wrote this code like 5 months ago, dont know what i was thinking

**Pull request closed without merging**
