### PR TITLE
Add ?> to songAdd.php because i think that does something

### PR DESCRIPTION
**Pull request by NoahGMD**

### CODE REVIEW

**Comment by NoahGMD** [comment]
if it doesn't do anything i will just delete this

**Comment by Jecket22** [comment]
Usually in never version of php it's not required I belive, but if there are versions that need this (which I didn't research so far) then this should be merged

**Comment by NoahGMD** [comment]
ok

**Comment by Cvolton** [comment]
This is not required in any version of PHP and in fact is known to cause issues in certain circumstances (unexpected whitespace characters in output)

**Pull request closed without merging**
