### PR TITLE
Added sort gauntlet.

### PR DESCRIPTION
**Pull request by Folleach**
Added column `sortBy` in table `gauntlet` for level sort.
Contains a column from the table `levels`.

### CODE REVIEW

**Comment by JeffreyRandom** [comment]
Help?
What do I have to put in the column `sortBy`?
I have to leave it null?

**Comment by Folleach** [comment]
> What do I have to put in the column `sortBy`?

You must specify the column name from the 'levels' table. 
> I have to leave it null?

If you leave 'null', then the sort will be the same as without this change.

For example, if you specify 'starStars' then the sorting will occur by the number of stars that the level has.
The order is descending.

**Comment by Zaxior** [comment]
How to make the order increases?

**Comment by Folleach** [comment]
> How to make the order increases?

No way in this commit.

**Comment by Zaxior** [comment]
Why?

**Comment by Folleach** [comment]
Sorting going on line 227 in the file "incl/levels/getGJLevels.php".
If making a change without new variable it can be breaking all level lists.

**Comment by GDBlackRed** [comment]
Please add an ASCENDING order.. It's hard to make a Gauntlet sort from it's Star Ratings

**Comment by Intelligent-Cat** [comment]
This could both be a bad thing and a good thing

**Comment by Folleach** [comment]
I don't like this implementation

**Pull request closed without merging**
