### PR TITLE
Upload limit: one level each 120 seconds

### PR DESCRIPTION
**Pull request by Aspoky**
Drop the request if the user have uploaded a level in the last 120 seconds.

### CODE REVIEW

**Comment by EMREOYUN** [comment]
Leaved a review, please check.

**Comment by Aspoky** [comment]
> Leaved a review, please check.

Where's the review?

**Comment by EMREOYUN** [comment]
Enter your code and you will find it.

**Comment by Aspoky** [comment]
> Enter your code and you will find it.

Give me the link, I can't find your comment anywhere

**Comment by EMREOYUN** [comment]
> > Enter your code and you will find it.
> 
> Give me the link, I can't find your comment anywhere

https://github.com/Cvolton/GMDprivateServer/pull/561/commits/54f4286ca51071729390e77d99933ba789613b25

**Comment by Cvolton** [comment]
Geometry Dash won't be able to read this error message, also rate limiting is already implemented (and was at the time of creation of pull requests) with the limit hardcoded to 60 seconds (see lines 126-133 in the current version of uploadGJLevel.php or lines 117-123 in your version)

**Pull request closed without merging**
