### PR TITLE
An account Verification System And Fixed a bug. 

### PR DESCRIPTION
**Pull request by WOSHIZHAZHA120**
Sorry for my english......

### CODE REVIEW

**Comment by bit0r1n** [comment]
Please, create SMTP configuration file in GDPS configuration directory like `~/config/smtp.php`

**Comment by EMREOYUN** [comment]
Tested this code, register not worked. Logins also doesn't work. No emails arrived to testing mail.

**Comment by WOSHIZHAZHA120** [comment]
> Tested this code, register not worked. Logins also doesn't work. No emails arrived to testing mail.

I tested, it's worked.

**Comment by WOSHIZHAZHA120** [comment]
> Tested this code, register not worked. Logins also doesn't work. No emails arrived to testing mail.

You can try adding "ssl://" at the beginning of the SMTP server address.

**Comment by EMREOYUN** [comment]
> > Tested this code, register not worked. Logins also doesn't work. No emails arrived to testing mail.
> 
> You can try adding "ssl://" at the beginning of the SMTP server address.

Well i'll try later im busy rn

**Pull request closed without merging**
