### PR TITLE
Fix autoban

### LINKED ISSUE #936: Autoban issue
It seems like autoban.php doesn't count daily levels and weekly demons, so it banning all people, who beated all levels + daily/weekly

image
image

### PR DESCRIPTION
**Pull request by MegaSa1nt**
Fixes #936

### CODE REVIEW

**Comment by MegaSa1nt** [comment]
not working rn

**Comment by MegaSa1nt** [comment]
@Cvolton

**Comment by MegaSa1nt** [comment]
Now it works

**Comment by Someone3601** [comment]
How do I use it?

**Pull request merged**
